## 爱快管理页面的 URL，结尾不要加 "/"，
## 如不填写，则使用第一个接口的网关地址作为爱快地址，
ikuai-url: http://10.0.0.1
username: admin # 爱快用户名
password: admin  #爱快密码
cron: 0 4 * * * # 执行更新的周期 crontab
custom-isp:     # 自定义运营商
  - name: CN  # 自定义运营商名称
    ## 自定义运营商 cidr 列表网址，每行一个，超过5000行会自动分为多个，ipv6 地址会被删除
    url: https://raw.githubusercontent.com/LidaoNote/OpenCode/refs/heads/main/china_ip.txt
